<?php 
	if (!defined('ABSPATH')) die();

	// Prefix
	define('MINT_PX' , 'mint_');

	// Documentation URL
	define('MINT_DOC_URL', 'http://help.1theme.com/mint/');

	// Support forum URL
	define("MINT_FORUM_URL", 'http://1theme.com/forums/mint');

	if (!defined('VC_SHORTCODE_CUSTOM_CSS_FILTER_TAG')) define('VC_SHORTCODE_CUSTOM_CSS_FILTER_TAG', '');

	// Socials
	$mint_social_networks = array(
		'facebook'       => 'Facebook',
		'flickr'         => 'Flickr',
		'vimeo'          => 'Vimeo',
		'twitter'        => 'Twitter',
		'gplus'          => 'Google Plus',
		'instagram'      => 'Instagram',
		'pinterest'      => 'Pinterest',
		'tumblr'         => 'Tumblr',
		'vkontakte'      => 'Vkontakte',
		'skype'          => 'Skype',
		'google-circles' => 'Google Circles',
		'github'         => 'Github',
		'linkedin'       => 'LinkedIn',
		'paypal'         => 'PayPal',
		'dribbble'       => 'Dribble',
		'soundcloud'     => 'SoundCloud',
		'stumbleupon'    => 'Stumble Upon',
		'picasa'         => 'Picasa',
		'lastfm'         => 'Last FM',
		'rdio'           => 'Rdio',
		'spotify'        => 'Spotfiy',
		'qq'             => 'qq.com',
		'dropbox'        => 'Dropbox',
		'evernote'       => 'Evernote',
		'flattr'         => 'Flattr',
		'renren'         => 'renren.com',
		'sina-weibo'     => 'Weibo',
		'mixi'           => 'Mixi',
		'behance'        => 'Behance',
		'smashing'       => 'Smashing'
   	);

	$mint_default_sidebars = array(
		'blog-sidebar',
		'footer-sidebar-1',
		'footer-sidebar-2',
		'footer-sidebar-3',
		'footer-sidebar-4',
		'mint-woocommerce'
	);
	
	// Registered navs var
	$mint_registered_menus = array();
	foreach(get_terms('nav_menu', array('hide_empty' => 0)) as $mmenu)
	{
		$mint_registered_menus[$mmenu->name] = '"'. $mmenu->name . '" &mdash; Menu';
	}
	

	// User
	if (is_user_logged_in()) 
	{
		$mint_current_user = wp_get_current_user();
	}
	else
	{
		$mint_current_user = false;
	}


	$mint_video_embed = (object)array(
			'youtube' => '<iframe width="%w%" height="%h%" src="//www.youtube-nocookie.com/embed/%id%" frameborder="0" allowfullscreen></iframe>',
			'vimeo'   => '<iframe src="//player.vimeo.com/video/%id%" width="%w%" height="%h%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',
			'html5'   => ''
 	);


 	$mint_entypo_icons = array(
 				"icon-plus",
				"icon-minus",
				"icon-info",
				"icon-left-thin",
				"icon-up-thin",
				"icon-right-thin",
				"icon-down-thin",
				"icon-level-up",
				"icon-level-down",
				"icon-switch",
				"icon-infinity",
				"icon-plus-squared",
				"icon-minus-squared",
				"icon-home",
				"icon-keyboard",
				"icon-erase",
				"icon-pause",
				"icon-fast-forward",
				"icon-fast-backward",
				"icon-to-end",
				"icon-to-start",
				"icon-hourglass",
				"icon-stop",
				"icon-up-dir",
				"icon-play",
				"icon-right-dir",
				"icon-down-dir",
				"icon-left-dir",
				"icon-adjust",
				"icon-cloud",
				"icon-star",
				"icon-star-empty",
				"icon-cup",
				"icon-menu",
				"icon-moon",
				"icon-heart-empty",
				"icon-heart",
				"icon-note",
				"icon-note-beamed",
				"icon-layout",
				"icon-flag",
				"icon-tools",
				"icon-cog",
				"icon-attention",
				"icon-flash",
				"icon-record",
				"icon-cloud-thunder",
				"icon-tape",
				"icon-flight",
				"icon-mail",
				"icon-pencil",
				"icon-feather",
				"icon-check",
				"icon-cancel",
				"icon-cancel-circled",
				"icon-cancel-squared",
				"icon-help",
				"icon-quote",
				"icon-plus-circled",
				"icon-minus-circled",
				"icon-right",
				"icon-direction",
				"icon-forward",
				"icon-ccw",
				"icon-cw",
				"icon-left",
				"icon-up",
				"icon-down",
				"icon-list-add",
				"icon-list",
				"icon-left-bold",
				"icon-right-bold",
				"icon-up-bold",
				"icon-down-bold",
				"icon-user-add",
				"icon-help-circled",
				"icon-info-circled",
				"icon-eye",
				"icon-tag",
				"icon-upload-cloud",
				"icon-reply",
				"icon-reply-all",
				"icon-code",
				"icon-export",
				"icon-print",
				"icon-retweet",
				"icon-comment",
				"icon-chat",
				"icon-vcard",
				"icon-address",
				"icon-location",
				"icon-map",
				"icon-compass",
				"icon-trash",
				"icon-doc",
				"icon-doc-text-inv",
				"icon-docs",
				"icon-doc-landscape",
				"icon-archive",
				"icon-rss",
				"icon-share",
				"icon-basket",
				"icon-shareable",
				"icon-login",
				"icon-logout",
				"icon-volume",
				"icon-resize-full",
				"icon-resize-small",
				"icon-popup",
				"icon-publish",
				"icon-window",
				"icon-arrow-combo",
				"icon-chart-pie",
				"icon-language",
				"icon-air",
				"icon-database",
				"icon-drive",
				"icon-bucket",
				"icon-thermometer",
				"icon-down-circled",
				"icon-left-circled",
				"icon-right-circled",
				"icon-up-circled",
				"icon-down-open",
				"icon-left-open",
				"icon-right-open",
				"icon-up-open",
				"icon-down-open-mini",
				"icon-left-open-mini",
				"icon-right-open-mini",
				"icon-up-open-mini",
				"icon-down-open-big",
				"icon-left-open-big",
				"icon-right-open-big",
				"icon-up-open-big",
				"icon-progress-0",
				"icon-progress-1",
				"icon-progress-2",
				"icon-progress-3",
				"icon-back-in-time",
				"icon-network",
				"icon-inbox",
				"icon-install",
				"icon-lifebuoy",
				"icon-mouse",
				"icon-dot",
				"icon-dot-2",
				"icon-dot-3",
				"icon-suitcase",
				"icon-flow-cascade",
				"icon-flow-branch",
				"icon-flow-tree",
				"icon-flow-line",
				"icon-flow-parallel",
				"icon-brush",
				"icon-paper-plane",
				"icon-magnet",
				"icon-gauge",
				"icon-traffic-cone",
				"icon-cc",
				"icon-cc-by",
				"icon-cc-nc",
				"icon-cc-nc-eu",
				"icon-cc-nc-jp",
				"icon-cc-sa",
				"icon-cc-nd",
				"icon-cc-pd",
				"icon-cc-zero",
				"icon-cc-share",
				"icon-cc-remix",
				"icon-github",
				"icon-github-circled",
				"icon-flickr",
				"icon-flickr-circled",
				"icon-vimeo",
				"icon-vimeo-circled",
				"icon-twitter",
				"icon-twitter-circled",
				"icon-facebook",
				"icon-facebook-circled",
				"icon-facebook-squared",
				"icon-gplus",
				"icon-gplus-circled",
				"icon-pinterest",
				"icon-pinterest-circled",
				"icon-tumblr",
				"icon-tumblr-circled",
				"icon-linkedin",
				"icon-linkedin-circled",
				"icon-dribbble",
				"icon-dribbble-circled",
				"icon-stumbleupon",
				"icon-stumbleupon-circled",
				"icon-lastfm",
				"icon-lastfm-circled",
				"icon-rdio",
				"icon-rdio-circled",
				"icon-spotify",
				"icon-spotify-circled",
				"icon-qq",
				"icon-instagram",
				"icon-dropbox",
				"icon-evernote",
				"icon-flattr",
				"icon-skype",
				"icon-skype-circled",
				"icon-renren",
				"icon-sina-weibo",
				"icon-paypal",
				"icon-picasa",
				"icon-soundcloud",
				"icon-mixi",
				"icon-behance",
				"icon-google-circles",
				"icon-vkontakte",
				"icon-smashing",
				"icon-db-shape",
				"icon-sweden",
				"icon-logo-db",
				"icon-picture",
				"icon-globe",
				"icon-leaf",
				"icon-graduation-cap",
				"icon-mic",
				"icon-palette",
				"icon-ticket",
				"icon-video",
				"icon-target",
				"icon-music",
				"icon-trophy",
				"icon-thumbs-up",
				"icon-thumbs-down",
				"icon-bag",
				"icon-user",
				"icon-users",
				"icon-lamp",
				"icon-alert",
				"icon-water",
				"icon-droplet",
				"icon-credit-card",
				"icon-monitor",
				"icon-briefcase",
				"icon-floppy",
				"icon-cd",
				"icon-folder",
				"icon-doc-text",
				"icon-calendar",
				"icon-chart-line",
				"icon-chart-bar",
				"icon-clipboard",
				"icon-attach",
				"icon-bookmarks",
				"icon-book",
				"icon-book-open",
				"icon-phone",
				"icon-megaphone",
				"icon-upload",
				"icon-download",
				"icon-box",
				"icon-newspaper",
				"icon-mobile",
				"icon-signal",
				"icon-camera",
				"icon-shuffle",
				"icon-loop",
				"icon-arrows-ccw",
				"icon-light-down",
				"icon-light-up",
				"icon-mute",
				"icon-sound",
				"icon-battery",
				"icon-search",
				"icon-key",
				"icon-lock",
				"icon-lock-open",
				"icon-bell",
				"icon-bookmark",
				"icon-link",
				"icon-back",
				"icon-flashlight",
				"icon-chart-area",
				"icon-clock",
				"icon-rocket",
				"icon-block"
		); 


	// Easing types
	$mint_easing = array(
		"linear",
		"easeInQuad",
		"easeOutQuad",
		"easeInOutQuad",
		"easeInCubic",
		"easeOutCubic",
		"easeInOutCubic",
		"easeInQuart",
		"easeOutQuart",
		"easeInOutQuart",
		"easeInQuint",
		"easeOutQuint",
		"easeInOutQuint",
		"easeInSine",
		"easeOutSine",
		"easeInOutSine",
		"easeInExpo",
		"easeOutExpo",
		"easeInOutExpo",
		"easeInCirc",
		"easeOutCirc",
		"easeInOutCirc",
		"easeInElastic",
		"easeOutElastic",
		"easeInOutElastic",
		"easeInBack",
		"easeOutBack",
		"easeInOutBack",
		"easeInBounce",
		"easeOutBounce",
		"easeInOutBounce",
	);


	// Once the shortcode of nivo will be at least once called, this variable should be set to true
	// Once this variable is set to true, all the required libs for nivo will be included
	$is_nivo = false;
?>